"""
Plain-language AI analysis for risk alerts, backed by a local Ollama model.

This is additive to the existing rule-based `description` field produced in
model.py's get_recent_alerts() -- that field stays as the fast, always-available
summary. This module adds a slower, on-demand explanation + recommendation,
generated by a local LLM, for admins who want more context on a specific alert.

Design constraints:
  - No new pip dependency: talks to Ollama's REST API directly with `requests`
    (already in requirements.txt).
  - Never raises out to the caller: any failure (Ollama not running, model not
    pulled, malformed response, timeout) returns a result dict with
    available=False and a human-readable reason, so the API/UI can degrade
    gracefully instead of erroring.
  - Results are meant to be cached by the caller (see app.py) keyed by alert
    id, since the underlying log row never changes once written.
"""

import json
import os

import requests

OLLAMA_HOST = os.environ.get("INSIGHTER_OLLAMA_HOST", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("INSIGHTER_OLLAMA_MODEL", "llama3.1:8b")
# 8B-parameter models on CPU-only hardware routinely take 20-90+ seconds for their
# FIRST response after being idle, since Ollama has to load several GB into RAM
# before generating a single token. 10s was too aggressive and caused every
# cold-start request to fail with "Ollama request timed out" even though Ollama
# was working correctly -- it just had not finished loading yet. This runs on a
# background QThread in the desktop app (see ai_worker.py), so a longer wait
# does not freeze the UI.
REQUEST_TIMEOUT_SECONDS = int(os.environ.get("INSIGHTER_OLLAMA_TIMEOUT_SECONDS", "90"))

SYSTEM_PROMPT = """You are a security analyst assistant embedded in an insider-threat \
monitoring dashboard called InSighter. You will be given structured data about one \
flagged alert: the user's role, the organizational sector, which behavioral signals \
triggered the flag, and the anomaly detection scores.

Respond with a short, plain-language explanation an IT administrator (not a data \
scientist) can read in a few seconds, plus one concrete, actionable recommendation \
for what to do next.

Rules:
- Do not just restate the numbers back; explain what they mean in context of the \
user's role and sector.
- The recommendation must be a specific next action (e.g. "review this user's file \
access log for the last 24 hours" or "confirm with their manager whether this login \
was expected"), not a vague statement like "monitor the situation."
- Respond with ONLY a JSON object, no other text, no markdown code fences, in \
exactly this shape:
{"explanation": "...", "recommendation": "..."}
"""


def _build_user_prompt(alert, sector, sector_config):
    return (
        f"Sector: {sector}\n"
        f"Sector monitored data categories: {', '.join(sector_config.get('data_categories', []))}\n"
        f"User: {alert.get('user')}\n"
        f"Role: {alert.get('role')}\n"
        f"Severity: {alert.get('severity')}\n"
        f"Flagged by: {alert.get('flagged_by')}\n"
        f"Rule-based summary: {alert.get('description')}\n"
        f"Login hour: {alert.get('login_hour')}\n"
        f"Files accessed: {alert.get('files_accessed')}\n"
        f"Data transferred (MB): {alert.get('data_transferred_mb')}\n"
        f"Failed logins: {alert.get('failed_logins')}\n"
        f"Isolation Forest score: {alert.get('if_score')}\n"
        f"One-Class SVM score: {alert.get('ocsvm_score')}\n"
        f"Blended risk score: {alert.get('final_score')}\n"
    )


def _unavailable(reason):
    return {"available": False, "reason": reason, "explanation": None, "recommendation": None}


def explain_alert(alert, sector, sector_config):
    """Call the local Ollama model to explain one alert. Never raises."""
    try:
        response = requests.post(
            f"{OLLAMA_HOST}/api/generate",
            json={
                "model": OLLAMA_MODEL,
                "system": SYSTEM_PROMPT,
                "prompt": _build_user_prompt(alert, sector, sector_config),
                "stream": False,
                "format": "json",
            },
            timeout=REQUEST_TIMEOUT_SECONDS,
        )
    except requests.exceptions.ConnectionError:
        return _unavailable(f"Ollama not running at {OLLAMA_HOST}")
    except requests.exceptions.Timeout:
        return _unavailable("Ollama request timed out")
    except requests.exceptions.RequestException as exc:
        return _unavailable(f"Ollama request failed: {exc}")

    if response.status_code == 404:
        return _unavailable(f"Model '{OLLAMA_MODEL}' not found — run `ollama pull {OLLAMA_MODEL}`")
    if not response.ok:
        return _unavailable(f"Ollama returned HTTP {response.status_code}")

    try:
        payload = response.json()
        raw_text = payload["response"]
        parsed = json.loads(raw_text)
        explanation = parsed["explanation"]
        recommendation = parsed["recommendation"]
    except (KeyError, ValueError, TypeError):
        return _unavailable("Could not parse a response from the model")

    return {
        "available": True,
        "reason": None,
        "explanation": explanation,
        "recommendation": recommendation,
    }
